import { mutation } from "./_generated/server";
import { v } from "convex/values";
import { api } from "./_generated/api";

/**
 * Mock AI function that generates an artifact and follow-up message
 * This is a placeholder - actual AI functionality will be implemented separately
 */
export const generateArtifact = mutation({
  args: {
    userMessage: v.string(),
    chatId: v.id("chats"),
  },
  handler: async (ctx, args) => {
    // Mock AI response - generates a simple artifact based on the user's request
    const mockArtifactTitle = `Document: ${args.userMessage.substring(0, 50)}...`;
    const mockArtifactContent = `# ${mockArtifactTitle}\n\nThis is a mock artifact generated in response to: "${args.userMessage}"\n\n## Content\n\nThis is placeholder content that would be generated by an AI assistant. In a real implementation, this would contain the actual generated text document.\n\nYou can edit this content in the rich text editor.`;
    const mockFollowUp = `I've created a document based on your request. You can edit it in the editor on the right.`;

    // Create the assistant message first
    const assistantMessageId = await ctx.db.insert("messages", {
      content: mockFollowUp,
      from_chat: args.chatId,
      has_artifact: null,
      metadata: { role: "assistant" },
    });

    // Create the artifact
    const artifactId = await ctx.db.insert("artifacts", {
      title: mockArtifactTitle,
      content: mockArtifactContent,
      from_message: assistantMessageId,
      from_chat: args.chatId,
    });

    // Update the message to reference the artifact
    await ctx.db.patch(assistantMessageId, {
      has_artifact: artifactId,
    });

    return {
      messageId: assistantMessageId,
      artifactId,
      content: mockFollowUp,
      artifact: {
        id: artifactId,
        title: mockArtifactTitle,
        content: mockArtifactContent,
      },
    };
  },
});
