# [Choice] Node.js version (use -bullseye variants on local arm64/Apple Silicon): 18, 16, 14, 18-bullseye, 16-bullseye, 14-bullseye, 18-buster, 16-buster, 14-buster
ARG NODE=22-bullseye
FROM mcr.microsoft.com/devcontainers/javascript-node:${NODE}

ARG ADDITIONAL_PACKAGES="fzf bat ripgrep"

RUN apt-get update && \
    apt-get install -yq --no-install-recommends ${ADDITIONAL_PACKAGES}